### ISSUE TITLE
Handling of non-unique keys

### ISSUE THREAD

**Issue by uweschaefer** [siosio/spring-cloud-aws-secrets-manager#2]
Hi & thanks for the useful library.

Context:
I have two secrets named "secret1" and "secret2" stored in the AWS secret manager, each consisting of a bunch of K/V Pairs. Both secrets have a key 'password'.

My limited understanding of SPEL is that there is no such thing as a namespace. 
Due to the fact, that all readable secrets are iterated and a map is created from their content, the second password will 'hide' the first.

Problem:
Given the above situation, i'd expect to resolve ${secret1.password} and ${secret2.password}.

I'll add a PR to add prefixing, even though i don't know what your position on this problem is:
a) resolve '${password}' as is and add '${secret1.password}' so that no code is broken and the user can choose, or
b) remove '${password}' and go with '${secret1.password}' for clarity, or
c) have a better idea, how to address this, or even explain why this is not a problem :)

Thanks for you time

**Comment by siosio** [comment]
Thanks for the issue.

It did not take into account that the secret name would overlap.
I will make improvements based on the proposed PR. 

Thank you.

**Comment by siosio** [comment]
applied the following.
`b) remove '$ {password}' and go with '$ {secret1.password}' for clarity, or`

Version 2.0.0 has been released.
